CREATE TABLE IF NOT EXISTS "TaskTags"(
    "id"   INTEGER PRIMARY KEY AUTOINCREMENT,
    "task" INTEGER NOT NULL,
    "tag"  INTEGER NOT NULL,
    FOREIGN KEY("task") REFERENCES "Task"("id"),
    FOREIGN KEY("tag")  REFERENCES "Tag"("id")
);
